title: Notre-Dame de Paris
baseURL: https://savethetimbersnyc.netlify.app
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 6
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Save the timbers NYC
    weight: 1
  es:
    contentDir: content/es
    title: Salvemos las maderas NYC
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: ''
  description: ''
  facebook: ''
  favicon: ''
  featured_image: /images/20180420_100315.jpg
  github: ''
  gitlab: ''
  instagram: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 6
  rss: ''
  site_logo: 'images/logo_test2.png'
  slack: ''
  stackoverflow: ''
  twitter: https://twitter.com/GoHugoIO
  youtube: ''
