title: Notre-Dame de Paris
baseURL: https://savethetimbersnyc.netlify.app
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Save the timbers NYC
    weight: 1
  es:
    contentDir: content/es
    title: Salvemos las maderas NYC
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: bg-black
  description: The last theme you'll ever need. Maybe.
  facebook: ''
  favicon: ''
  featured_image: /images/IMG_0224.png
  github: ''
  gitlab: ''
  instagram: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: https://twitter.com/GoHugoIO
  youtube: ''
